-- Run this once in Supabase Dashboard → SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id text primary key,
  brand_name text not null default 'Let''s Match',
  title text not null default 'Slide into this form ✨',
  description text not null default 'A fun, colorful, social-app-inspired form experience.',
  source_form_url text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.form_fields (
  id bigint generated by default as identity primary key,
  google_field_id text,
  google_entry_id text,
  sort_order integer not null,
  label text not null,
  description text,
  field_type text not null,
  required boolean not null default false,
  options jsonb not null default '[]'::jsonb,
  raw_type integer,
  raw_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  answers jsonb not null default '{}'::jsonb,
  answer_by_field jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.app_settings (id) values ('main') on conflict (id) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.admin_users enable row level security;
alter table public.app_settings enable row level security;
alter table public.form_fields enable row level security;
alter table public.submissions enable row level security;

-- Remove policies if you rerun this script.
drop policy if exists "admin can view own admin row" on public.admin_users;
drop policy if exists "public can read settings" on public.app_settings;
drop policy if exists "admins manage settings" on public.app_settings;
drop policy if exists "public can read form fields" on public.form_fields;
drop policy if exists "admins manage form fields" on public.form_fields;
drop policy if exists "public can submit" on public.submissions;
drop policy if exists "admins can read submissions" on public.submissions;
drop policy if exists "admins can delete submissions" on public.submissions;

create policy "admin can view own admin row"
on public.admin_users for select to authenticated
using ((select auth.uid()) = user_id);

create policy "public can read settings"
on public.app_settings for select to anon, authenticated
using (true);

create policy "admins manage settings"
on public.app_settings for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "public can read form fields"
on public.form_fields for select to anon, authenticated
using (true);

create policy "admins manage form fields"
on public.form_fields for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "public can submit"
on public.submissions for insert to anon, authenticated
with check (true);

create policy "admins can read submissions"
on public.submissions for select to authenticated
using ((select public.is_admin()));

create policy "admins can delete submissions"
on public.submissions for delete to authenticated
using ((select public.is_admin()));

grant select on public.app_settings to anon, authenticated;
grant select on public.form_fields to anon, authenticated;
grant insert on public.submissions to anon, authenticated;
grant select, insert, update, delete on public.app_settings to authenticated;
grant select, insert, update, delete on public.form_fields to authenticated;
grant select, delete on public.submissions to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- AFTER creating your admin user in Supabase Authentication → Users,
-- replace the UUID below and run this separately:
-- insert into public.admin_users (user_id) values ('YOUR_AUTH_USER_UUID');
