-- Run this once in Supabase Dashboard → SQL Editor.
-- It creates the database, security policies, and the exact form fields shown in the supplied screenshots.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id text primary key,
  brand_name text not null default 'Let''s Match',
  title text not null default 'Find your people. Build something together. ✨',
  description text not null default 'Tell us who you are, what you''re building, what you can offer, and what you''re looking for.',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.form_fields (
  id bigint generated by default as identity primary key,
  google_field_id text,
  google_entry_id text,
  sort_order integer not null,
  label text not null,
  description text,
  field_type text not null,
  required boolean not null default false,
  options jsonb not null default '[]'::jsonb,
  raw_type integer,
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  answers jsonb not null default '{}'::jsonb,
  answer_by_field jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.app_settings (id, brand_name, title, description, active)
values (
  'main',
  'Let''s Match',
  'Find your people. Build something together. ✨',
  'Tell us who you are, what you''re building, what you can offer, and what you''re looking for.',
  true
)
on conflict (id) do update set
  brand_name = excluded.brand_name,
  title = excluded.title,
  description = excluded.description;

-- Exact question schema supplied by the user.
-- Safe to rerun: this refreshes only the questions, not existing submissions.
delete from public.form_fields;

insert into public.form_fields (sort_order, label, description, field_type, required, options, raw_data) values
(1, 'Email', null, 'email', true, '[]'::jsonb, '{"autocomplete":"email","placeholder":"you@example.com"}'::jsonb),
(2, 'Your Whatsapp Number', 'we will use this to add to Whatsapp Group', 'tel', false, '[]'::jsonb, '{"autocomplete":"tel","placeholder":"+49 … / +91 …"}'::jsonb),
(3, 'Your Name', null, 'text', true, '[]'::jsonb, '{"autocomplete":"name","placeholder":"What should we call you?"}'::jsonb),
(4, 'Current City / Country', 'we would use this to decide venue of physical meet up.', 'text', false, '[]'::jsonb, '{"placeholder":"e.g. Berlin, Germany"}'::jsonb),
(5, 'Who am I', 'Few words about yourself', 'paragraph', true, '[]'::jsonb, '{"placeholder":"Tell the community a little about you…"}'::jsonb),
(6, 'What I''m obsessed with (currently) / building', 'Mention anything you are passionate about', 'paragraph', true, '[]'::jsonb, '{"placeholder":"What has your attention right now?"}'::jsonb),
(7, 'One thing I can help with:', 'Tell people what you are good at', 'paragraph', true, '[]'::jsonb, '{"placeholder":"Your superpower, skill, experience…"}'::jsonb),
(8, 'One thing I''m looking for', 'How you intend to benefit from this Community?', 'paragraph', true, '[]'::jsonb, '{"placeholder":"Co-founder? Feedback? Network? Inspiration?"}'::jsonb),
(9, 'Which statement best describes your current involvement?', null, 'multiple_choice', false,
 '["I am actively building a startup/product now","I have a clear idea and am looking for collaborators/co-founders.","I am actively looking for an idea/problem to solve, and join others","I want to learn, network, and offer feedback","I want to join and get inspired."]'::jsonb, '{}'::jsonb),
(10, 'What is your primary domain/skill set? (Select all that apply)', null, 'checkboxes', false,
 '["Engineering/Coding","Product Management/Strategy","Marketing/Growth","Sales/BizDev","Design/UX","Other"]'::jsonb,
 '{"allow_other":true,"other_label":"Other"}'::jsonb),
(11, 'Have you been involved in a startup/project before?', null, 'multiple_choice', false, '["Yes","No"]'::jsonb, '{}'::jsonb),
(12, 'If yes, please provide a Link to your Startup/project or describe it.', null, 'paragraph', false, '[]'::jsonb, '{"placeholder":"Paste a link or describe the project…"}'::jsonb),
(13, 'Any Remarks, additional information', null, 'paragraph', false, '[]'::jsonb, '{"placeholder":"Anything else you''d like us to know?"}'::jsonb),
(14, 'I consent to the processing of my personal data for the purposes of community management and internal networking.', null, 'consent', true, '["Yes, I consent"]'::jsonb, '{}'::jsonb);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.admin_users enable row level security;
alter table public.app_settings enable row level security;
alter table public.form_fields enable row level security;
alter table public.submissions enable row level security;

drop policy if exists "admin can view own admin row" on public.admin_users;
drop policy if exists "public can read settings" on public.app_settings;
drop policy if exists "admins manage settings" on public.app_settings;
drop policy if exists "public can read form fields" on public.form_fields;
drop policy if exists "admins manage form fields" on public.form_fields;
drop policy if exists "public can submit" on public.submissions;
drop policy if exists "admins can read submissions" on public.submissions;
drop policy if exists "admins can delete submissions" on public.submissions;

create policy "admin can view own admin row"
on public.admin_users for select to authenticated
using ((select auth.uid()) = user_id);

create policy "public can read settings"
on public.app_settings for select to anon, authenticated
using (true);

create policy "admins manage settings"
on public.app_settings for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "public can read form fields"
on public.form_fields for select to anon, authenticated
using (true);

create policy "admins manage form fields"
on public.form_fields for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "public can submit"
on public.submissions for insert to anon, authenticated
with check (true);

create policy "admins can read submissions"
on public.submissions for select to authenticated
using ((select public.is_admin()));

create policy "admins can delete submissions"
on public.submissions for delete to authenticated
using ((select public.is_admin()));

grant select on public.app_settings to anon, authenticated;
grant select on public.form_fields to anon, authenticated;
grant insert on public.submissions to anon, authenticated;
grant select, insert, update, delete on public.app_settings to authenticated;
grant select, insert, update, delete on public.form_fields to authenticated;
grant select, delete on public.submissions to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- AFTER creating your admin user in Supabase Authentication → Users,
-- copy that user's UUID and run this separately:
-- insert into public.admin_users (user_id) values ('YOUR_AUTH_USER_UUID');
